# Generated by Django 6.0.2 on 2026-03-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_ordernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernotification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
