# Generated by GPT-5.2 on 2026-03-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_ordernotification_id'),
        ('products', '0022_order_delivery_dates'),
    ]

    operations = []

