# Generated by Django 6.0.2 on 2026-03-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_remove_order_coupon_code_remove_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
