# Generated by Django 6.0.2 on 2026-03-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_remove_review_product_flashsale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='description',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='bulky_surcharge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bulky',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='town',
            name='base_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='town',
            name='estimated_days',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='flashsale',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
