# Generated by Django 6.0.2 on 2026-03-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_remove_coupon_description_order_shipping_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionStrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Buy Two | Get 10% Off', max_length=255)),
                ('bg_color', models.CharField(default='#9c27b0', help_text='Hex color e.g. #9c27b0 for purple', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance on homepage')),
                ('products', models.ManyToManyField(related_name='promotion_strips', to='products.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
