# Generated by Django 6.0.2 on 2026-03-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_promotionstrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionstrip',
            name='discount_percent',
            field=models.PositiveIntegerField(default=10, help_text='Percent to deduct'),
        ),
        migrations.AddField(
            model_name='promotionstrip',
            name='min_quantity',
            field=models.PositiveIntegerField(default=2, help_text='Quantity to trigger discount'),
        ),
        migrations.AlterField(
            model_name='promotionstrip',
            name='bg_color',
            field=models.CharField(default='#9c27b0', help_text='Hex color code', max_length=20),
        ),
        migrations.AlterField(
            model_name='promotionstrip',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order on homepage'),
        ),
        migrations.AlterField(
            model_name='promotionstrip',
            name='title',
            field=models.CharField(help_text='e.g. Buy 2 Get 10% Off', max_length=255),
        ),
    ]
