# Generated by Django 6.0.2 on 2026-03-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_promotionstrip_discount_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBubble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='bubbles/')),
                ('link_url', models.CharField(help_text='e.g. /products/?category=1', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
