# Generated by Django 6.0.2 on 2026-03-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_homebubble'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebubble',
            name='link_url',
        ),
        migrations.AddField(
            model_name='homebubble',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='home_bubbles', to='products.product'),
        ),
    ]
