# Generated by Django 6.0.2 on 2026-03-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_remove_homebubble_link_url_homebubble_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionstrip',
            name='badge_text',
            field=models.CharField(blank=True, help_text="Optional: e.g. 'Add 2 to Cart Get 10%'", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='promotionstrip',
            name='bg_color',
            field=models.CharField(default='#9c27b0', max_length=20),
        ),
        migrations.AlterField(
            model_name='promotionstrip',
            name='discount_percent',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='promotionstrip',
            name='min_quantity',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='promotionstrip',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promotionstrip',
            name='title',
            field=models.CharField(help_text='Internal name for the strip line', max_length=255),
        ),
    ]
